language: python
dist: xenial
python:
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
env:
  - MC_VERSION=1.16.1
before_install:
  - wget https://raw.githubusercontent.com/python-pillow/Pillow/master/src/libImaging/Imaging.h
  - wget https://raw.githubusercontent.com/python-pillow/Pillow/master/src/libImaging/ImagingUtils.h
  - wget https://raw.githubusercontent.com/python-pillow/Pillow/master/src/libImaging/ImPlatform.h
install:
  - pip install -q pillow
  - pip install -q numpy
  - pip install -q networkx
  - pip install -q pytest
  - python3 setup.py build
before_script:
  - git clone git://github.com/overviewer/Minecraft-Overviewer-Addons.git ~/mcoa/
  - mkdir -p ~/.minecraft/versions/${MC_VERSION}/
  - wget -N https://overviewer.org/textures/${MC_VERSION} -O ~/.minecraft/versions/${MC_VERSION}/${MC_VERSION}.jar
script:
  - pytest
  - python3 overviewer.py ~/mcoa/exmaple ~/test-output --rendermodes=smooth-lighting -p1
notifications:
  email: false
