language: python
python:
  # - "2.6"
  - "2.7"
  # - "3.2"
env:
  - MC_VERSION=1.13
before_install:
  - wget https://raw.githubusercontent.com/python-pillow/Pillow/master/src/libImaging/Imaging.h
  - wget https://raw.githubusercontent.com/python-pillow/Pillow/master/src/libImaging/ImagingUtils.h
  - wget https://raw.githubusercontent.com/python-pillow/Pillow/master/src/libImaging/ImPlatform.h
install:
  - pip install -q pillow
  - pip install -q numpy
  - python setup.py build
before_script:
  - git clone git://github.com/overviewer/Minecraft-Overviewer-Addons.git ~/mcoa/
  - mkdir -p ~/.minecraft/versions/${MC_VERSION}/
  - wget -N https://launcher.mojang.com/mc/game/1.13/client/c0b970952cdd279912da384cdbfc0c26e6c6090b/client.jar -O ~/.minecraft/versions/${MC_VERSION}/${MC_VERSION}.jar
script:
  - PYTHONPATH=. python test/test_all.py
  - python overviewer.py ~/mcoa/exmaple ~/test-output --rendermodes=smooth-lighting -p1
notifications:
  email: false
  irc:
    channels:
      - "chat.freenode.net#overviewer"
    template:
      - "\x0313Minecraft-Overviewer\x03/\x0306%{branch}\x03 \x0314%{commit}\x03 %{build_url} %{message}"
# matrix:
  # allow_failures:
    # - python: "3.2"
